import { RpgContentBundle } from "./content-types";

export const frameworkBaseContent: RpgContentBundle = {
  dialogues: [
    {
      id: "guard_intro",
      startNodeId: "start",
      nodes: [
        {
          id: "start",
          speaker: "Guard",
          text: "Halt traveler. State your business.",
          choices: [
            {
              id: "friendly_greeting",
              text: "I'm here to help the village.",
              nextNodeId: "help_offer",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: 5 }],
            },
            {
              id: "threaten_guard",
              text: "Out of my way.",
              nextNodeId: "hostile_reply",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: -10 }],
            },
          ],
        },
        {
          id: "help_offer",
          speaker: "Guard",
          text: "Then help us clear the rogue sentry in the ruins.",
          choices: [
            {
              id: "accept_job",
              text: "I'll handle it.",
              endsDialogue: true,
              effects: [
                { type: "set_flag", flag: "accepted_ruin_job", value: true },
                { type: "emit_event", eventId: "quest:talk:Guard" },
              ],
            },
          ],
        },
        {
          id: "hostile_reply",
          speaker: "Guard",
          text: "Watch your tongue. You're close to being barred from the gate.",
          choices: [
            {
              id: "leave",
              text: "Fine. I'm leaving.",
              endsDialogue: true,
            },
          ],
        },
      ],
    },
    {
      id: "merchant_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Merchant",
          text: "Welcome, traveler! Care to browse my wares? I've fresh stock from the capital.",
          choices: [
            {
              id: "buy",
              text: "I'd like to trade.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open" }],
            },
            {
              id: "rumors",
              text: "Any news from the road?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Just passing through.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Merchant",
          text: "Strange lights in the old ruins to the east. Locals say undead stir there. I say good business — adventurers pay well for potions.",
          choices: [
            {
              id: "thanks",
              text: "Good to know. Thanks.",
              endsDialogue: true,
            },
          ],
        },
      ],
    },
    {
      id: "innkeeper_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Innkeeper",
          text: "Welcome to the Broken Lantern. We've hot stew and dry beds. What'll it be?",
          choices: [
            {
              id: "rest",
              text: "I need a room for the night.",
              nextNodeId: "rest_reply",
              conditions: [],
            },
            {
              id: "rumors",
              text: "Heard anything interesting lately?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Nothing for now.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rest_reply",
          speaker: "Innkeeper",
          text: "10 gold for a full night. Coin first, questions later.",
          choices: [
            {
              id: "pay",
              text: "Here you go. (10 gold)",
              endsDialogue: true,
              effects: [
                { type: "consume_item", itemId: "gold_coins", quantity: 10 },
                { type: "emit_event", eventId: "rest:inn" },
              ],
            },
            {
              id: "decline",
              text: "Maybe later.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Innkeeper",
          text: "Guards found a body near the south gate this morning. Nobody saw a thing — or nobody's talking.",
          choices: [
            { id: "back", text: "Hmm. Thanks.", endsDialogue: true },
          ],
        },
      ],
    },
  ],
  quests: [
    {
      id: "quest_guard_resolution",
      name: "Guard Resolution",
      description: "Speak with the guard and resolve the ruins threat.",
      xpReward: 100,
      startNodeIds: ["talk_to_guard"],
      nodes: [
        {
          id: "talk_to_guard",
          description: "Talk to the guard captain.",
          triggerType: "talk",
          targetId: "Guard",
          requiredCount: 1,
          nextNodeIds: ["defeat_ruin_guard"],
        },
        {
          id: "defeat_ruin_guard",
          description: "Defeat the rogue ruin guard.",
          triggerType: "kill",
          targetId: "RuinGuard",
          requiredCount: 1,
        },
      ],
    },
    {
      id: "quest_bandit_bounty",
      name: "Bandit Bounty",
      description: "The village has posted a bounty on the bandits harassing the trade road.",
      xpReward: 150,
      startNodeIds: ["kill_bandits"],
      nodes: [
        {
          id: "kill_bandits",
          description: "Eliminate 3 bandits on the trade road.",
          triggerType: "kill",
          targetId: "Bandit",
          requiredCount: 3,
          nextNodeIds: ["collect_proof"],
        },
        {
          id: "collect_proof",
          description: "Pick up a bandit token as proof.",
          triggerType: "pickup",
          targetId: "bandit_token",
          requiredCount: 1,
        },
      ],
    },
  ],
  items: [
    {
      id: "iron_sword",
      name: "Iron Sword",
      description: "Reliable steel for close quarters.",
      stackable: false,
      slot: "mainHand",
      tags: ["weapon", "melee"],
    },
    {
      id: "iron_shield",
      name: "Iron Shield",
      description: "A battered but functional shield.",
      stackable: false,
      slot: "offHand",
      tags: ["armor", "shield"],
    },
    {
      id: "leather_helmet",
      name: "Leather Helmet",
      description: "Lightweight head protection for scouts and rogues.",
      stackable: false,
      slot: "head",
      tags: ["armor", "light"],
    },
    {
      id: "iron_chestplate",
      name: "Iron Chestplate",
      description: "Heavy chest armor for frontline warriors.",
      stackable: false,
      slot: "chest",
      tags: ["armor", "heavy"],
    },
    {
      id: "health_potion",
      name: "Health Potion",
      description: "Restores 30 HP when consumed.",
      stackable: true,
      maxStack: 25,
      tags: ["consumable", "potion"],
    },
    {
      id: "magicka_potion",
      name: "Magicka Potion",
      description: "Restores 30 MP when consumed.",
      stackable: true,
      maxStack: 25,
      tags: ["consumable", "potion"],
    },
    {
      id: "guard_token",
      name: "Guard Token",
      description: "An insignia of the village guard. May be used as quest proof.",
      stackable: true,
      maxStack: 10,
      tags: ["quest"],
    },
    {
      id: "bandit_token",
      name: "Bandit Token",
      description: "Evidence of a dispatched bandit. Redeemable for bounty.",
      stackable: true,
      maxStack: 10,
      tags: ["quest"],
    },
    {
      id: "gold_coins",
      name: "Gold Coins",
      description: "The common currency of the realm.",
      stackable: true,
      maxStack: 9999,
      tags: ["currency"],
    },
    {
      id: "shortbow",
      name: "Shortbow",
      description: "A compact hunting bow with decent draw weight.",
      stackable: false,
      slot: "mainHand",
      tags: ["weapon", "ranged", "bow"],
    },
  ],
  factions: [
    {
      id: "village_guard",
      name: "Village Guard",
      description: "Protectors of the frontier settlement.",
      defaultReputation: 0,
      hostileBelow: -25,
      friendlyAt: 25,
      alliedAt: 60,
    },
    {
      id: "bandits",
      name: "Bandit Brotherhood",
      description: "Outlaws who prey on travelers and merchants.",
      defaultReputation: -50,
      hostileBelow: 0,
      friendlyAt: 100,
      alliedAt: 100,
    },
    {
      id: "merchants_guild",
      name: "Merchants Guild",
      description: "A trade association that regulates commerce across the region.",
      defaultReputation: 10,
      hostileBelow: -40,
      friendlyAt: 20,
      alliedAt: 50,
    },
    {
      id: "mages_college",
      name: "Mages College",
      description: "An order of arcane scholars and spellcasters.",
      defaultReputation: 0,
      hostileBelow: -30,
      friendlyAt: 30,
      alliedAt: 70,
    },
  ],
  npcArchetypes: [
    {
      id: "archetype_guard",
      name: "Town Guard",
      description: "A disciplined guard who patrols the settlement perimeter.",
      role: "guard",
      factionId: "village_guard",
      isHostile: false,
      isMerchant: false,
      dialogueId: "guard_intro",
      lootTableId: "common_loot",
      baseHealth: 120,
      level: 3,
      skills: { "one_handed": 40, "block": 35, "heavy_armor": 40 },
      disposition: 50,
      respawns: true,
    },
    {
      id: "archetype_bandit",
      name: "Bandit",
      description: "A lawless outlaw who attacks on sight.",
      role: "enemy",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "bandit_loot",
      baseHealth: 80,
      level: 2,
      skills: { "one_handed": 30, "light_armor": 25 },
      disposition: 10,
      respawns: true,
    },
    {
      id: "archetype_merchant",
      name: "Traveling Merchant",
      description: "A wandering trader with eclectic wares.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      dialogueId: "merchant_intro",
      baseHealth: 60,
      level: 1,
      skills: { "speechcraft": 55, "mercantile": 60 },
      disposition: 60,
      respawns: false,
    },
    {
      id: "archetype_bandit_chief",
      name: "Bandit Chief",
      description: "A powerful bandit leader with heavy armor and strong attacks.",
      role: "boss",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "dungeon_loot",
      baseHealth: 200,
      level: 6,
      skills: { "one_handed": 55, "block": 50, "heavy_armor": 55 },
      disposition: 5,
      respawns: false,
    },
    {
      id: "archetype_innkeeper",
      name: "Innkeeper",
      description: "The proprietor of the local inn — offers beds, food, and gossip.",
      role: "innkeeper",
      isHostile: false,
      isMerchant: true,
      dialogueId: "innkeeper_intro",
      baseHealth: 70,
      level: 1,
      skills: { "speechcraft": 45, "mercantile": 40 },
      disposition: 65,
      respawns: false,
    },
    {
      id: "archetype_villager",
      name: "Villager",
      description: "An ordinary citizen going about daily life.",
      role: "villager",
      isHostile: false,
      isMerchant: false,
      baseHealth: 50,
      level: 1,
      skills: {},
      disposition: 55,
      respawns: false,
    },
    {
      id: "archetype_mage_apprentice",
      name: "Mage Apprentice",
      description: "A junior mage who casts fire and frost spells from range.",
      role: "enemy",
      factionId: "mages_college",
      isHostile: false,
      isMerchant: false,
      baseHealth: 65,
      level: 3,
      skills: { "destruction": 45, "alteration": 30 },
      disposition: 40,
      respawns: true,
    },
  ],
};
