import { RpgContentBundle } from "./content-types";

export const frameworkBaseContent: RpgContentBundle = {
  dialogues: [
    {
      id: "guard_intro",
      startNodeId: "start",
      nodes: [
        {
          id: "start",
          speaker: "Guard",
          text: "Halt traveler. State your business.",
          choices: [
            {
              id: "friendly_greeting",
              text: "I'm here to help the village.",
              nextNodeId: "help_offer",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: 5 }],
            },
            {
              id: "threaten_guard",
              text: "Out of my way.",
              nextNodeId: "hostile_reply",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: -10 }],
            },
          ],
        },
        {
          id: "help_offer",
          speaker: "Guard",
          text: "Then help us clear the rogue sentry in the ruins.",
          choices: [
            {
              id: "accept_job",
              text: "I'll handle it.",
              endsDialogue: true,
              effects: [
                { type: "set_flag", flag: "accepted_ruin_job", value: true },
                { type: "emit_event", eventId: "quest:talk:Guard" },
              ],
            },
          ],
        },
        {
          id: "hostile_reply",
          speaker: "Guard",
          text: "Watch your tongue. You're close to being barred from the gate.",
          choices: [
            {
              id: "leave",
              text: "Fine. I'm leaving.",
              endsDialogue: true,
            },
          ],
        },
      ],
    },
    {
      id: "merchant_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Merchant",
          text: "Welcome, traveler! Care to browse my wares? I've fresh stock from the capital.",
          choices: [
            {
              id: "buy",
              text: "I'd like to trade.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_01" } }],
            },
            {
              id: "rumors",
              text: "Any news from the road?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Just passing through.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Merchant",
          text: "Strange lights in the old ruins to the east. Locals say undead stir there. I say good business — adventurers pay well for potions.",
          choices: [
            {
              id: "thanks",
              text: "Good to know. Thanks.",
              endsDialogue: true,
            },
          ],
        },
      ],
    },
    {
      id: "innkeeper_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Innkeeper",
          text: "Welcome to the Broken Lantern. We've hot stew and dry beds. What'll it be?",
          choices: [
            {
              id: "rest",
              text: "I need a room for the night.",
              nextNodeId: "rest_reply",
              conditions: [],
            },
            {
              id: "rumors",
              text: "Heard anything interesting lately?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Nothing for now.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rest_reply",
          speaker: "Innkeeper",
          text: "10 gold for a full night. Coin first, questions later.",
          choices: [
            {
              id: "pay",
              text: "Here you go. (10 gold)",
              endsDialogue: true,
              conditions: [{ type: "has_item", itemId: "gold_coins", minQuantity: 10 }],
              effects: [
                { type: "consume_item", itemId: "gold_coins", quantity: 10 },
                { type: "emit_event", eventId: "rest:inn", payload: { hours: 8 } },
              ],
            },
            {
              id: "decline",
              text: "Maybe later.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Innkeeper",
          text: "Guards found a body near the south gate this morning. Nobody saw a thing — or nobody's talking.",
          choices: [
            { id: "back", text: "Hmm. Thanks.", endsDialogue: true },
          ],
        },
      ],
    },
    {
      id: "barkeeper_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Barkeeper",
          text: "What can I get you? Ale, mead, or something to eat? The stew's fresh.",
          choices: [
            {
              id: "buy_ale",
              text: "I'll have an ale. (2 gold)",
              nextNodeId: "ale_reply",
              conditions: [{ type: "has_item", itemId: "gold_coins", minQuantity: 2 }],
              effects: [
                { type: "consume_item", itemId: "gold_coins", quantity: 2 },
                { type: "give_item", itemId: "ale", quantity: 1 },
              ],
            },
            {
              id: "buy_mead",
              text: "A mug of mead, please. (3 gold)",
              nextNodeId: "mead_reply",
              conditions: [{ type: "has_item", itemId: "gold_coins", minQuantity: 3 }],
              effects: [
                { type: "consume_item", itemId: "gold_coins", quantity: 3 },
                { type: "give_item", itemId: "mead", quantity: 1 },
              ],
            },
            {
              id: "buy_stew",
              text: "A bowl of stew. (4 gold)",
              nextNodeId: "food_reply",
              conditions: [{ type: "has_item", itemId: "gold_coins", minQuantity: 4 }],
              effects: [
                { type: "consume_item", itemId: "gold_coins", quantity: 4 },
                { type: "give_item", itemId: "stew", quantity: 1 },
              ],
            },
            {
              id: "rumors",
              text: "Heard anything worth knowing?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Nothing for me right now.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "ale_reply",
          speaker: "Barkeeper",
          text: "Coming right up. Nothing cures the road like a cold ale.",
          choices: [
            { id: "back", text: "Thanks.", nextNodeId: "greet" },
            { id: "leave", text: "Cheers.", endsDialogue: true },
          ],
        },
        {
          id: "mead_reply",
          speaker: "Barkeeper",
          text: "Finest mead this side of the hills. Brewed it myself.",
          choices: [
            { id: "back", text: "Much appreciated.", nextNodeId: "greet" },
            { id: "leave", text: "Excellent.", endsDialogue: true },
          ],
        },
        {
          id: "food_reply",
          speaker: "Barkeeper",
          text: "Here you go. Stick to your ribs on a cold night.",
          choices: [
            { id: "back", text: "Smells good.", nextNodeId: "greet" },
            { id: "leave", text: "Much better.", endsDialogue: true },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Barkeeper",
          text: "There's been talk of trouble on the eastern trade road. Merchants coming in short a few guards. Whatever's out there, it's bold.",
          choices: [
            { id: "back", text: "Interesting. Thanks.", nextNodeId: "greet" },
            { id: "leave", text: "I'll keep my eyes open.", endsDialogue: true },
          ],
        },
      ],
    },
    {
      id: "shopkeeper_general_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Shopkeeper",
          text: "Welcome! I carry a bit of everything — tools, supplies, the odd trinket. Take a look around.",
          choices: [
            {
              id: "trade",
              text: "Let me see what you have.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_general_01" } }],
            },
            {
              id: "rumors",
              text: "Heard anything useful lately?",
              nextNodeId: "rumors_reply",
            },
            {
              id: "leave",
              text: "Just passing through.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "rumors_reply",
          speaker: "Shopkeeper",
          text: "Word is the old garrison road is clear again. Good news for supply caravans — and for anyone moving goods quietly.",
          choices: [
            {
              id: "trade",
              text: "Good to know. Let me browse.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_general_01" } }],
            },
            { id: "leave", text: "Thanks.", endsDialogue: true },
          ],
        },
      ],
    },
    {
      id: "shopkeeper_weapons_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Weapons Dealer",
          text: "Looking for steel? I've got blades, bows, and hafts to suit every fighting style. Quality guaranteed.",
          choices: [
            {
              id: "trade",
              text: "Show me your weapons.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_weapons_01" } }],
            },
            {
              id: "ask_repair",
              text: "Can you repair my gear?",
              nextNodeId: "repair_reply",
            },
            {
              id: "leave",
              text: "Not today.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "repair_reply",
          speaker: "Weapons Dealer",
          text: "Leave it on the counter. I charge by the condition — badly damaged pieces cost more to fix right.",
          choices: [
            {
              id: "trade",
              text: "Fair enough. Let's see prices.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_weapons_01" } }],
            },
            { id: "leave", text: "I'll think about it.", endsDialogue: true },
          ],
        },
      ],
    },
    {
      id: "shopkeeper_armor_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Armorer",
          text: "Good protection is worth every coin. Plate, leather, chain — I stock them all. What are you after?",
          choices: [
            {
              id: "trade",
              text: "Let me see your stock.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_armor_01" } }],
            },
            {
              id: "ask_light",
              text: "What would you recommend for someone who moves fast?",
              nextNodeId: "light_reply",
            },
            {
              id: "ask_heavy",
              text: "I want the heaviest protection you have.",
              nextNodeId: "heavy_reply",
            },
            {
              id: "leave",
              text: "Not right now.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "light_reply",
          speaker: "Armorer",
          text: "Leather cuirass and bracers. Lets you move, deflects glancing blows. Rangers and scouts swear by it.",
          choices: [
            {
              id: "trade",
              text: "Show me.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_armor_01" } }],
            },
            { id: "leave", text: "I'll keep that in mind.", endsDialogue: true },
          ],
        },
        {
          id: "heavy_reply",
          speaker: "Armorer",
          text: "Iron plate. It'll slow you down, but you'll weather hits that would drop a lesser fighter.",
          choices: [
            {
              id: "trade",
              text: "That sounds like what I need.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_armor_01" } }],
            },
            { id: "leave", text: "I'll think it over.", endsDialogue: true },
          ],
        },
      ],
    },
    {
      id: "shopkeeper_alchemist_intro",
      startNodeId: "greet",
      nodes: [
        {
          id: "greet",
          speaker: "Alchemist",
          text: "Ah, a curious visitor. I deal in potions, reagents, and the odd curiosity. Mind the fumes — some of these mixtures are… temperamental.",
          choices: [
            {
              id: "trade",
              text: "I'd like to browse your potions.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_alchemist_01" } }],
            },
            {
              id: "ask_lore",
              text: "What can you tell me about alchemy?",
              nextNodeId: "lore_reply",
            },
            {
              id: "leave",
              text: "I was just looking.",
              endsDialogue: true,
            },
          ],
        },
        {
          id: "lore_reply",
          speaker: "Alchemist",
          text: "Every ingredient has properties — some heal, some harm, some do things I'm still cataloguing. "
            + "Combine two that share a property and you get a potion. "
            + "Combine opposing ones and… well, that's how I lost my eyebrows.",
          choices: [
            {
              id: "trade",
              text: "Fascinating. Let me see what you have.",
              endsDialogue: true,
              effects: [{ type: "emit_event", eventId: "barter:open", payload: { merchantId: "merchant_alchemist_01" } }],
            },
            { id: "leave", text: "Noted. I'll be careful.", endsDialogue: true },
          ],
        },
      ],
    },
  ],
  quests: [
    {
      id: "quest_guard_resolution",
      name: "Guard Resolution",
      description: "Speak with the guard and resolve the ruins threat.",
      xpReward: 100,
      startNodeIds: ["talk_to_guard"],
      nodes: [
        {
          id: "talk_to_guard",
          description: "Talk to the guard captain.",
          triggerType: "talk",
          targetId: "Guard",
          requiredCount: 1,
          nextNodeIds: ["defeat_ruin_guard"],
        },
        {
          id: "defeat_ruin_guard",
          description: "Defeat the rogue ruin guard.",
          triggerType: "kill",
          targetId: "RuinGuard",
          requiredCount: 1,
        },
      ],
    },
    {
      id: "quest_bandit_bounty",
      name: "Bandit Bounty",
      description: "The village has posted a bounty on the bandits harassing the trade road.",
      xpReward: 150,
      startNodeIds: ["kill_bandits"],
      nodes: [
        {
          id: "kill_bandits",
          description: "Eliminate 3 bandits on the trade road.",
          triggerType: "kill",
          targetId: "Bandit",
          requiredCount: 3,
          nextNodeIds: ["collect_proof"],
        },
        {
          id: "collect_proof",
          description: "Pick up a bandit token as proof.",
          triggerType: "pickup",
          targetId: "bandit_token",
          requiredCount: 1,
        },
      ],
    },
  ],
  items: [
    {
      id: "iron_sword",
      name: "Iron Sword",
      description: "Reliable steel for close quarters.",
      stackable: false,
      slot: "mainHand",
      tags: ["weapon", "melee"],
    },
    {
      id: "iron_shield",
      name: "Iron Shield",
      description: "A battered but functional shield.",
      stackable: false,
      slot: "offHand",
      tags: ["armor", "shield"],
    },
    {
      id: "leather_helmet",
      name: "Leather Helmet",
      description: "Lightweight head protection for scouts and rogues.",
      stackable: false,
      slot: "head",
      tags: ["armor", "light"],
    },
    {
      id: "iron_chestplate",
      name: "Iron Chestplate",
      description: "Heavy chest armor for frontline warriors.",
      stackable: false,
      slot: "chest",
      tags: ["armor", "heavy"],
    },
    {
      id: "health_potion",
      name: "Health Potion",
      description: "Restores 30 HP when consumed.",
      stackable: true,
      maxStack: 25,
      tags: ["consumable", "potion"],
    },
    {
      id: "magicka_potion",
      name: "Magicka Potion",
      description: "Restores 30 MP when consumed.",
      stackable: true,
      maxStack: 25,
      tags: ["consumable", "potion"],
    },
    {
      id: "guard_token",
      name: "Guard Token",
      description: "An insignia of the village guard. May be used as quest proof.",
      stackable: true,
      maxStack: 10,
      tags: ["quest"],
    },
    {
      id: "bandit_token",
      name: "Bandit Token",
      description: "Evidence of a dispatched bandit. Redeemable for bounty.",
      stackable: true,
      maxStack: 10,
      tags: ["quest"],
    },
    {
      id: "gold_coins",
      name: "Gold Coins",
      description: "The common currency of the realm.",
      stackable: true,
      maxStack: 9999,
      tags: ["currency"],
    },
    {
      id: "shortbow",
      name: "Shortbow",
      description: "A compact hunting bow with decent draw weight.",
      stackable: false,
      slot: "mainHand",
      tags: ["weapon", "ranged", "bow"],
    },
    {
      id: "ale",
      name: "Ale",
      description: "A frothy mug of ale. Takes the edge off a long day.",
      stackable: true,
      maxStack: 10,
      tags: ["consumable", "drink"],
    },
    {
      id: "mead",
      name: "Mead",
      description: "A rich honeyed mead. Warming and sweet.",
      stackable: true,
      maxStack: 10,
      tags: ["consumable", "drink"],
    },
    {
      id: "wine",
      name: "Wine",
      description: "A goblet of red wine. Favored by merchants and nobles.",
      stackable: true,
      maxStack: 10,
      tags: ["consumable", "drink"],
    },
    {
      id: "bread",
      name: "Bread",
      description: "A loaf of fresh-baked bread. Simple but filling.",
      stackable: true,
      maxStack: 10,
      tags: ["consumable", "food"],
    },
    {
      id: "stew",
      name: "Hot Stew",
      description: "A hearty bowl of meat and vegetable stew. Restores stamina.",
      stackable: true,
      maxStack: 5,
      tags: ["consumable", "food"],
    },
    {
      id: "cheese",
      name: "Cheese",
      description: "A wedge of aged cheese. A traveler's staple.",
      stackable: true,
      maxStack: 10,
      tags: ["consumable", "food"],
    },
  ],
  factions: [
    {
      id: "village_guard",
      name: "Village Guard",
      description: "Protectors of the frontier settlement.",
      defaultReputation: 0,
      hostileBelow: -25,
      friendlyAt: 25,
      alliedAt: 60,
    },
    {
      id: "bandits",
      name: "Bandit Brotherhood",
      description: "Outlaws who prey on travelers and merchants.",
      defaultReputation: -50,
      hostileBelow: 0,
      friendlyAt: 100,
      alliedAt: 100,
    },
    {
      id: "merchants_guild",
      name: "Merchants Guild",
      description: "A trade association that regulates commerce across the region.",
      defaultReputation: 10,
      hostileBelow: -40,
      friendlyAt: 20,
      alliedAt: 50,
    },
    {
      id: "mages_college",
      name: "Mages College",
      description: "An order of arcane scholars and spellcasters.",
      defaultReputation: 0,
      hostileBelow: -30,
      friendlyAt: 30,
      alliedAt: 70,
    },
  ],
  npcArchetypes: [
    {
      id: "archetype_guard",
      name: "Town Guard",
      description: "A disciplined guard who patrols the settlement perimeter.",
      role: "guard",
      factionId: "village_guard",
      isHostile: false,
      isMerchant: false,
      dialogueId: "guard_intro",
      lootTableId: "common_loot",
      baseHealth: 120,
      level: 3,
      skills: { "one_handed": 40, "block": 35, "heavy_armor": 40 },
      disposition: 50,
      respawns: true,
    },
    {
      id: "archetype_bandit",
      name: "Bandit",
      description: "A lawless outlaw who attacks on sight.",
      role: "enemy",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "bandit_loot",
      baseHealth: 80,
      level: 2,
      skills: { "one_handed": 30, "light_armor": 25 },
      disposition: 10,
      respawns: true,
      // Light leather armor provides minimal physical protection
      damageResistances: { physical: 0.08 },
    },
    {
      id: "archetype_merchant",
      name: "Traveling Merchant",
      description: "A wandering trader with eclectic wares.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      dialogueId: "merchant_intro",
      baseHealth: 60,
      level: 1,
      skills: { "speechcraft": 55, "mercantile": 60 },
      disposition: 60,
      respawns: false,
    },
    {
      id: "archetype_bandit_chief",
      name: "Bandit Chief",
      description: "A powerful bandit leader with heavy armor and strong attacks.",
      role: "boss",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "dungeon_loot",
      baseHealth: 200,
      level: 6,
      skills: { "one_handed": 55, "block": 50, "heavy_armor": 55 },
      disposition: 5,
      respawns: false,
      // Heavy armor grants meaningful physical resistance; fire burns through steel
      damageResistances: { physical: 0.25 },
      damageWeaknesses: { fire: 0.2 },
    },
    {
      id: "archetype_innkeeper",
      name: "Innkeeper",
      description: "The proprietor of the local inn — offers beds, food, and gossip.",
      role: "innkeeper",
      isHostile: false,
      isMerchant: true,
      dialogueId: "innkeeper_intro",
      baseHealth: 70,
      level: 1,
      skills: { "speechcraft": 45, "mercantile": 40 },
      disposition: 65,
      respawns: false,
    },
    {
      id: "archetype_villager",
      name: "Villager",
      description: "An ordinary citizen going about daily life.",
      role: "villager",
      isHostile: false,
      isMerchant: false,
      baseHealth: 50,
      level: 1,
      skills: {},
      disposition: 55,
      respawns: false,
    },
    {
      id: "archetype_mage_apprentice",
      name: "Mage Apprentice",
      description: "A junior mage who casts fire and frost spells from range.",
      role: "enemy",
      factionId: "mages_college",
      isHostile: false,
      isMerchant: false,
      baseHealth: 65,
      level: 3,
      skills: { "destruction": 45, "alteration": 30 },
      disposition: 40,
      respawns: true,
      // Arcane training provides partial resistance to magic elements but slight
      // physical vulnerability (robes offer little protection)
      damageResistances: { fire: 0.15, frost: 0.15, shock: 0.15 },
      damageWeaknesses: { physical: 0.1 },
    },
    {
      id: "archetype_barkeeper",
      name: "Barkeeper",
      description: "The bar operator — serves drinks and food, and always knows the latest gossip.",
      role: "innkeeper",
      isHostile: false,
      isMerchant: false,
      dialogueId: "barkeeper_intro",
      baseHealth: 65,
      level: 1,
      skills: { "speechcraft": 50, "mercantile": 35 },
      disposition: 70,
      respawns: false,
      voiceType: "neutral",
      personalityTraits: ["friendly"],
    },
    {
      id: "archetype_shopkeeper_general",
      name: "General Goods Merchant",
      description: "Stocks everyday supplies — food, tools, and common adventuring necessities.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      dialogueId: "shopkeeper_general_intro",
      baseHealth: 60,
      level: 1,
      skills: { "speechcraft": 45, "mercantile": 55 },
      disposition: 60,
      respawns: false,
      voiceType: "neutral",
      personalityTraits: ["friendly", "greedy"],
    },
    {
      id: "archetype_shopkeeper_weapons",
      name: "Weapons Dealer",
      description: "A seasoned fighter turned merchant who sells quality blades and bows.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      dialogueId: "shopkeeper_weapons_intro",
      baseHealth: 80,
      level: 2,
      skills: { "speechcraft": 35, "mercantile": 45, "one_handed": 50, "two_handed": 40 },
      disposition: 55,
      respawns: false,
      voiceType: "neutral",
      personalityTraits: ["brave"],
    },
    {
      id: "archetype_shopkeeper_armor",
      name: "Armorer",
      description: "Crafts and sells protective gear ranging from leather to iron plate.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      dialogueId: "shopkeeper_armor_intro",
      baseHealth: 90,
      level: 2,
      skills: { "speechcraft": 35, "mercantile": 45, "heavy_armor": 55, "light_armor": 40 },
      disposition: 55,
      respawns: false,
      voiceType: "neutral",
    },
    {
      id: "archetype_shopkeeper_alchemist",
      name: "Alchemist",
      description: "A knowledgeable potion-maker and ingredient dealer with an eye for the unusual.",
      role: "merchant",
      factionId: "mages_college",
      isHostile: false,
      isMerchant: true,
      dialogueId: "shopkeeper_alchemist_intro",
      baseHealth: 55,
      level: 2,
      skills: { "speechcraft": 40, "mercantile": 40, "alchemy": 65 },
      disposition: 60,
      respawns: false,
      voiceType: "neutral",
      personalityTraits: ["cunning"],
    },
  ],
};
