import { RpgContentBundle } from "./content-types";

export const frameworkBaseContent: RpgContentBundle = {
  dialogues: [
    {
      id: "guard_intro",
      startNodeId: "start",
      nodes: [
        {
          id: "start",
          speaker: "Guard",
          text: "Halt traveler. State your business.",
          choices: [
            {
              id: "friendly_greeting",
              text: "I'm here to help the village.",
              nextNodeId: "help_offer",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: 5 }],
            },
            {
              id: "threaten_guard",
              text: "Out of my way.",
              nextNodeId: "hostile_reply",
              effects: [{ type: "faction_delta", factionId: "village_guard", amount: -10 }],
            },
          ],
        },
        {
          id: "help_offer",
          speaker: "Guard",
          text: "Then help us clear the rogue sentry in the ruins.",
          choices: [
            {
              id: "accept_job",
              text: "I'll handle it.",
              endsDialogue: true,
              effects: [
                { type: "set_flag", flag: "accepted_ruin_job", value: true },
                { type: "emit_event", eventId: "quest:talk:Guard" },
              ],
            },
          ],
        },
        {
          id: "hostile_reply",
          speaker: "Guard",
          text: "Watch your tongue. You're close to being barred from the gate.",
          choices: [
            {
              id: "leave",
              text: "Fine. I'm leaving.",
              endsDialogue: true,
            },
          ],
        },
      ],
    },
  ],
  quests: [
    {
      id: "quest_guard_resolution",
      name: "Guard Resolution",
      description: "Speak with the guard and resolve the ruins threat.",
      xpReward: 100,
      startNodeIds: ["talk_to_guard"],
      nodes: [
        {
          id: "talk_to_guard",
          description: "Talk to the guard captain.",
          triggerType: "talk",
          targetId: "Guard",
          requiredCount: 1,
          nextNodeIds: ["defeat_ruin_guard"],
        },
        {
          id: "defeat_ruin_guard",
          description: "Defeat the rogue ruin guard.",
          triggerType: "kill",
          targetId: "RuinGuard",
          requiredCount: 1,
        },
      ],
    },
  ],
  items: [
    {
      id: "iron_sword",
      name: "Iron Sword",
      description: "Reliable steel for close quarters.",
      stackable: false,
      slot: "mainHand",
      tags: ["weapon", "melee"],
    },
    {
      id: "health_potion",
      name: "Health Potion",
      description: "Restores health.",
      stackable: true,
      maxStack: 25,
      tags: ["consumable"],
    },
  ],
  factions: [
    {
      id: "village_guard",
      name: "Village Guard",
      description: "Protectors of the frontier settlement.",
      defaultReputation: 0,
      hostileBelow: -25,
      friendlyAt: 25,
      alliedAt: 60,
    },
  ],
  npcArchetypes: [
    {
      id: "archetype_guard",
      name: "Town Guard",
      description: "A disciplined guard who patrols the settlement perimeter.",
      role: "guard",
      factionId: "village_guard",
      isHostile: false,
      isMerchant: false,
      dialogueId: "guard_intro",
      lootTableId: "common_loot",
      baseHealth: 120,
      level: 3,
      skills: { "one_handed": 40, "block": 35, "heavy_armor": 40 },
      disposition: 50,
      respawns: true,
    },
    {
      id: "archetype_bandit",
      name: "Bandit",
      description: "A lawless outlaw who attacks on sight.",
      role: "enemy",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "bandit_loot",
      baseHealth: 80,
      level: 2,
      skills: { "one_handed": 30, "light_armor": 25 },
      disposition: 10,
      respawns: true,
    },
    {
      id: "archetype_merchant",
      name: "Traveling Merchant",
      description: "A wandering trader with eclectic wares.",
      role: "merchant",
      factionId: "merchants_guild",
      isHostile: false,
      isMerchant: true,
      baseHealth: 60,
      level: 1,
      skills: { "speechcraft": 55, "mercantile": 60 },
      disposition: 60,
      respawns: false,
    },
    {
      id: "archetype_bandit_chief",
      name: "Bandit Chief",
      description: "A powerful bandit leader with heavy armor and strong attacks.",
      role: "boss",
      factionId: "bandits",
      isHostile: true,
      isMerchant: false,
      lootTableId: "dungeon_loot",
      baseHealth: 200,
      level: 6,
      skills: { "one_handed": 55, "block": 50, "heavy_armor": 55 },
      disposition: 5,
      respawns: false,
    },
    {
      id: "archetype_innkeeper",
      name: "Innkeeper",
      description: "The proprietor of the local inn — offers beds, food, and gossip.",
      role: "innkeeper",
      isHostile: false,
      isMerchant: true,
      baseHealth: 70,
      level: 1,
      skills: { "speechcraft": 45, "mercantile": 40 },
      disposition: 65,
      respawns: false,
    },
    {
      id: "archetype_villager",
      name: "Villager",
      description: "An ordinary citizen going about daily life.",
      role: "villager",
      isHostile: false,
      isMerchant: false,
      baseHealth: 50,
      level: 1,
      skills: {},
      disposition: 55,
      respawns: false,
    },
  ],
};
